package com.example.CheckoutService.api.service;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import com.example.CheckoutService.api.model.History;

import java.util.List;


// Repo interface describes how to interact w/ DB using custom operations. It's
// implementation is auto generated by spring boot.
public interface HistoryRepository extends JpaRepository<History, Long>{

    @Query(value = "SELECT * FROM history WHERE sellerID = ?1", nativeQuery = true)
    List<History> findBySellerID(String sellerID);

    @Query(value = "SELECT * FROM history WHERE buyerID= ?1", nativeQuery = true)
    List<History> findByBuyerID(String buyerID);

    @Query(value = "SELECT * FROM history WHERE listing_title LIKE %?1%", nativeQuery = true)
    List<History> findByListingTitle(String listingTitle);
}
